### ISSUE TITLE
Implement health-checks / status 

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-autocluster#17]
Implement some command to check the cluster status, and integrate them with `rabbitmqctl-diagnostics`

We can also have a look this [Mirantis commit](https://github.com/Mirantis/rabbitmq-autocluster/commit/5fee57752a0788bd2358d3f09eae76d4da67f039)

**Comment by michaelklishin** [comment]
By the time `rabbitmq-diagnostics` ships much of this plugin will be in the core or separate plugins. I'd recommend not bothering with that just yet and doing it in the new individual backend plugins when they are mostly fleshed out.

**Comment by michaelklishin** [comment]
What can be done already is a command that lists the peers known to the discovery backend (using the list operation we already have in master).
