### ISSUE TITLE
Rename the plugin name to rabbitmq_autocluster

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-autocluster#31]
The plugin name does not follow the standard names.

The current name is `autocluster` and should be renamed to  `rabbitmq_autocluster`.

**Comment by michaelklishin** [comment]
More specifically, starting with 3.7.0/master plugins must depend on the `rabbit` app and should the `rabbitmq_` prefix. Plugins that don't won't break but it won't be possible to list or activate them.

**Comment by michaelklishin** [comment]
This was addressed in #33. Note that if you have this repo cloned as `deps/autocluster` it must be re-cloned (or moved) as `deps/rabbitmq_autocluster` now.
