### ISSUE TITLE
When serviceName changed, the cluster doesn`t work.

### ISSUE THREAD

**Issue by tianctrl** [rabbitmq/rabbitmq-autocluster#35]
I modify the value "serviceName" in statefulset yaml and "name" in service yaml together. 
example both are "rabbitmq2", like this:

`metadata:
  name: rabbitmq
  namespace: test-rabbitmq
spec:
  serviceName: rabbitmq2
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq`

`kind: Service
apiVersion: v1
metadata:
  namespace: test-rabbitmq
  name: rabbitmq2
  labels:
    app: rabbitmq
    type: LoadBalancer  `

then the rabbitmq node can not found each other. Just when the value is "rabbitmq", the cluster working fine.

**Comment by tianctrl** [comment]
Soryy!!  It`s my fault again. 
A configuration called  "K8S Service Name"  , I  forgot it. I missed it. 
Just now, I saw this ENV in readme.  I hope the ohers come in here, saw this, would not make the same mistake as me.
I`m sorry for create an issue again, and actually it is not an issue, just my mistake.
BTW, I must say , you people doing a great work, figure out my tough problem.

**Comment by michaelklishin** [comment]
@tianctrl please use rabbitmq-users for questions in the future. This team does not use Github issues for questions, investigations, RCA.
