### ISSUE TITLE
Docker image build

### ISSUE THREAD

**Issue by adrianchifor** [rabbitmq/rabbitmq-autocluster#36]
Hi, I was following the steps in 
https://github.com/rabbitmq/rabbitmq-autocluster/tree/master/examples/k8s_statefulsets 
to build the Docker image but I get the following error when starting the service on k8s:
```
14:36:44.684 [error] Failed to enable plugin "rabbitmq_autocluster": it may have been built with an incompatible (more recent?) version of Erlang

BOOT FAILED
===========

Error description:
    init:start_em/1
    init:start_it/1
    rabbit:start_it/1 line 454
    rabbit:broker_start/0 line 326
    rabbit_plugins:prepare_plugins/1 line 285
    rabbit_plugins:'-prepare_plugins/1-lc$^1/1-1-'/1 line 285
    rabbit_plugins:prepare_dir_plugin/1 line 449
throw:{plugin_built_with_incompatible_erlang,"rabbitmq_autocluster"}
Log file(s) (may contain more information):
   <stdout>

{"init terminating in do_boot",{plugin_built_with_incompatible_erlang,"rabbitmq_autocluster"}}
```

I build it using erlang 20.0 and elixir 1.4.5. I saw after that the dev requirements mention erlang 17.5 but I wasn't able to find an elixir version that works with erlang 17.5 so I'm not sure how you guys are building it.

Is the Docker image at https://hub.docker.com/r/gsantomaggio/rabbitmq-autocluster/ built using the same steps from the master branch?

**Comment by michaelklishin** [comment]
The image uses [Dockerfile from the stable branch](https://github.com/rabbitmq/rabbitmq-autocluster/blob/stable/Dockerfile).

The error means that the plugin failed to load, most likely because it was compiled on a different version of Erlang from that on which RabbitMQ is running.

**Comment by michaelklishin** [comment]
`master` targets RabbitMQ master. I'd recommend using [the stable branch](https://github.com/rabbitmq/rabbitmq-autocluster/tree/stable/examples/k8s_statefulsets) unless you know what you're doing and why you want RabbitMQ master.

**Comment by adrianchifor** [comment]
@michaelklishin thanks for the info. What version of elixir are you guys using when running `make dist` ?

**Comment by michaelklishin** [comment]
@adrianchifor `stable` targets RabbitMQ 3.6.x which doesn't use Elixir at all.

**Comment by michaelklishin** [comment]
`0.8.0` was produced on Erlang/OTP 19.3.6.

**Comment by michaelklishin** [comment]
I think @Gsantomaggio know what may be going on. At least one of the images that use this plugin is currently on Erlang 18, which isn't guaranteed to load bytecode files produced by 19.3. We are not aware of any cases where 20 would be unable to load bytecode produced by 19.

**Comment by Gsantomaggio** [comment]
hi @adrianchifor

https://hub.docker.com/r/gsantomaggio/rabbitmq-autocluster/  is/was my personal temporary image.

we are moving the image here:
https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-autocluster/

So if you want to test this example:
https://github.com/rabbitmq/rabbitmq-autocluster/tree/stable/examples/k8s_statefulsets  


you can to  skip the `make` and `build` image steps.

you can use `pivotalrabbitmq/rabbitmq-autocluster` image instead of  [rabbitmq-autocluster](https://github.com/rabbitmq/rabbitmq-autocluster/blob/stable/examples/k8s_statefulsets/rabbitmq.yaml#L16)  in the `rabbitmq.yaml` file. 

We will update the example soon.

**Comment by adrianchifor** [comment]
@Gsantomaggio excellent, thanks a lot!

**Comment by michaelklishin** [comment]
@adrianchifor done in #37.
