### ISSUE TITLE
Docker image tag

### ISSUE THREAD

**Issue by adrianchifor** [rabbitmq/rabbitmq-autocluster#39]
Hey guys, can we please have the [docker image](https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-autocluster/tags/) tagged with the version of the release on GitHub? We don't want to keep pulling the latest image in case it breaks.

**Comment by Gsantomaggio** [comment]
Hi @adrianchifor 

This image is an help to run/understand easily the [examples](https://github.com/rabbitmq/rabbitmq-autocluster/tree/stable/examples) 

But what we could do is:

1. Follow the RabbitMQ version with the last `rabbitmq-autoclsuter` version. Something like `rabbitmq-autocluster:3.6.10` and add on the descriptions the `rabbitmq-autocluster` [version](https://github.com/rabbitmq/rabbitmq-autocluster/releases) it is using.

2. Follow both RabbitMQ and Autocluster version something like:
`rabbitmq-autocluster:3.6.10-autocluster-0.80` (or similar)

My original idea was the option 1.

Thoughts @michaelklishin @dcorbacho ?

**Comment by michaelklishin** [comment]
I think option 1 would be sufficient.

**Comment by adrianchifor** [comment]
Actually, option 2 might be a bit thorough, since tags on docker images should be a snapshot of a specific commit and not change after (except the latest tag and security fixes). Since this is the autocluster image, might be a better idea to have the image tag the same as the release tag on GitHub, people will look into what version of rabbitmq is used in a specific autocluster release.

**Comment by michaelklishin** [comment]
@adrianchifor this plugin doesn't really have a strict dependency on a particular RabbitMQ version (it primarily uses internal functions that rarely change). #40 introduces a way to specify the plugin version you want. Generally images should target the most recent RabbitMQ release. If that's not what you want, well, the `Dockerfile` is quite small and there really isn't much to installing and enabling this plugin.

**Comment by Gsantomaggio** [comment]
Going to update https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-autocluster with `rabbitmq-autocluster:3.6.10` and `rabbitmq-autocluster:latest`

**Comment by Gsantomaggio** [comment]
Done: https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-autocluster/tags/

Execute `rabbitmq-plugins list` command to know the auto-cluster version: 
```
/ # rabbitmq-plugins list
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   [failed to contact rabbit@5b299a2378b1 - status not shown]
 |/
[e ] amqp_client                       3.6.10
[E ] autocluster                       0.8.0
[e ] cowboy                            1.0.4
[e ] cowlib                            1.0.2
[  ] rabbitmq_amqp1_0                  3.6.10

....

```
