### ISSUE TITLE
Please support microsoft service fabric on linux and maybe windows too

### ISSUE THREAD

**Issue by AceHack** [rabbitmq/rabbitmq-autocluster#48]
Service fabric supports running on Linux, it can run docker containers, it has a service discovery service named the naming service much like consul and it can even run docker compose files and it even has it's own DNS service that can facilitate service discovery based on the state in the naming service.  Please add this is a supported backend, it would be amazing.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-docker-compose
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-and-communicate-with-services

**Comment by AceHack** [comment]
Here is a windows nanoserver-insider docker image for rabbit if that helps getting it supported on windows at all.
[rabbitmq-nanoserver-insider.zip](https://github.com/rabbitmq/rabbitmq-autocluster/files/1289342/rabbitmq-nanoserver-insider.zip)

**Comment by AceHack** [comment]
Okay I've added the autocluster plugin and setup SSL.  I'm now working on Service Fabric integration using DNS.
[rabbitmq-nanoserver-insider.zip](https://github.com/rabbitmq/rabbitmq-autocluster/files/1351200/rabbitmq-nanoserver-insider.zip)

**Comment by michaelklishin** [comment]
Thanks but we decided that #68 will be the last new addition for this plugin since it's on life support. We'd welcome Service Fabric support for the [3.7.x peer discovery subsystem](http://www.rabbitmq.com/blog/2018/02/12/peer-discovery-subsystem-in-rabbitmq-3-7/) as a separate (and much smaller) plugin.
