### ISSUE TITLE
AWS: Use PTR records for discovered instances

### ISSUE THREAD

**Issue by alexander-shlygin-epam** [rabbitmq/rabbitmq-autocluster#69]
AWS plugin returns privateDNS field or ip address as hostname for discovered instances in cluster. PrivateDNS always has ip-xx format. It would be nice to have a way to use own hostnames for instances discovered with AWS plugin. The best way I see is private ip name lookup instead of using privateDNS fields.

**Comment by michaelklishin** [comment]
This plugin is on life support and won't be getting any new features besides (perhaps) #68.

**Comment by michaelklishin** [comment]
New features would be considered for [peer-discovery-backend-aws](https://github.com/rabbitmq/rabbitmq-peer-discovery-aws/) but I'm not sure how many are interested in PTR record support. Flexible hostnames are supported by Consul, for example, and it introduced a lot of complexity yet it's not a commonly used feature. If reverse DNS lookups are desired they can be used via the DNS backend: not exactly the same thing but an option nonetheless.

Private IP addresses and DNS have been sufficient for a lot of users over the course of several years in this plugin.
