### ISSUE TITLE
Mirroring

### ISSUE THREAD

**Issue by consult-kk** [rabbitmq/rabbitmq-autocluster#71]
Hi,
This plugin appears to work only with the pivotal image and not the base rabbitmq 3.6.x image.
I also need to enable mirroring , but the pods ends up "PostHookError".
This is what I have in the kube spec YML file , can you please help me on this :- 
( the yml formatting is all messed up with this editor, but otherwise it is well-formed )
[....]
`lifecycle:`
`           postStart:`
`              exec:`
`                 command:`
`                 - /bin/sh`
`                 - -c`
`                 - >`
`                   sleep 1m && rabbitmqctl set_policy queue-mirror-ha ".*" '{"ha-mode":"all","ha-sync-mode": "automatic"}' --apply-to queues`
[....]

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ 3.6.x has been EOL'ed for months now. Consider [upgrading](http://www.rabbitmq.com/upgrade.html) to [3.7.x](http://www.rabbitmq.com/changelog.html) where this plugin [is no longer necessary](http://www.rabbitmq.com/cluster-formation.html).
