### ISSUE TITLE
Unable to configure using environment variables

### ISSUE THREAD

**Issue by Teketel** [rabbitmq/rabbitmq-autocluster#72]
I am not able to configure RMQ default user name, password and vhost name using environment variables. The container starts with default user name and password `guest`.

This is the command i used to run a container 
`docker run -d --name rabbitmq --net=host -p 4369:4369 -p 5672:5672 -p 15672:15672 -p 25672:25672 -e RABBITMQ_DEFAULT_PASS=<MyPassWord> -e RABBITMQ_DEFAULT_USER=<MyUserName> -e RABBITMQ_DEFAULT_VHOST=<MyVHost> -e AUTOCLUSTER_TYPE=aws -e AWS_AUTOSCALING=true -e AUTOCLUSTER_CLEANUP=true -e CLEANUP_WARN_ONLY=false -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION pivotalrabbitmq/rabbitmq-autocluster`

Can some one help me if i miss something?

**Comment by lukebakken** [comment]
Did you see this? https://github.com/docker-library/rabbitmq/issues/150

Please follow up from here on the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. Thanks.
